/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.snethlios.utils.Auth;
import com.snethlios.utils.MsgBox;
import com.snethlios.utils.XImage;
import event.EventMenuSelected;
import form.BanHangJPanel1;
import form.ChaoJDialog;
import form.DangNhapJDialog11;
import form.DoiMKJPanel;
import form.KhachHangJPanel;
import form.KhuyenMaiJPanel;
import form.LichSuJPanel;
import form.NewJPanel;
import form.NhanVienJPanel;
import form.SanPhamJPanel;
import form.ThongKeJPanel;
import form.TrangChuJPanel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;

/**
 *
 * @author Admin
 */
public class MainJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private ThongKeJPanel thongKe;
    private NewJPanel test;
    private TrangChuJPanel trangChu;
    private SanPhamJPanel sanPham;
    private KhuyenMaiJPanel khuyenMai;
    private BanHangJPanel1 banHang;
    private NhanVienJPanel nhanVien;
    private KhachHangJPanel khachHang;
    private DoiMKJPanel doiMK;
    private LichSuJPanel lichSu;
//    private DangNhapJDialog11 login;

    public MainJFrame1() {
        initComponents();
        init();
        trangChu = new TrangChuJPanel();
        thongKe = new ThongKeJPanel();
        test = new NewJPanel();
        try {
            banHang = new BanHangJPanel1();
        } catch (SQLException ex) {
            Logger.getLogger(MainJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        sanPham = new SanPhamJPanel();
        khuyenMai = new KhuyenMaiJPanel();
        nhanVien = new NhanVienJPanel();
        khachHang = new KhachHangJPanel();
        doiMK = new DoiMKJPanel();
        lichSu = new LichSuJPanel();

        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    setForm(trangChu);
                } else if (index == 1) {
                    setForm(banHang);
                    try {
                        banHang.loadTableSanPham();
                        banHang.loadTableHoaDon();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainJFrame1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (index == 2) {
                    setForm(sanPham);
                    sanPham.fillComboboxKhuyenMai();
                } else if (index == 3) {
                    setForm(khuyenMai);
                } else if (index == 4) {
                    setForm(lichSu);
                    lichSu.loadTablePhieuXuat();
                } else if (index == 5) {
                    setForm(thongKe);
                    thongKe.fillTableBang();
                } else if (index == 6) {
                    setForm(khachHang);
                } else if (index == 7) {
                    setForm(nhanVien);
                } else if (index == 8) {
                    setForm(doiMK);
                } else if (index == 9) {
                    if (MsgBox.confirm(test, "Bạn Có Muốn Kết Thúc?")) {
                        dangXuat();
                    }

                }
            }
        });
        //  set when system open start with home form

        setForm(new TrangChuJPanel());
    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorderJPanel1 = new swing.PanelBorderJPanel();
        menu = new component.MenuJPanel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBorderJPanel1.setBackground(new java.awt.Color(247, 247, 247));

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorderJPanel1Layout = new javax.swing.GroupLayout(panelBorderJPanel1);
        panelBorderJPanel1.setLayout(panelBorderJPanel1Layout);
        panelBorderJPanel1Layout.setHorizontalGroup(
            panelBorderJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderJPanel1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
        );
        panelBorderJPanel1Layout.setVerticalGroup(
            panelBorderJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderJPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderJPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private component.MenuJPanel menu;
    private swing.PanelBorderJPanel panelBorderJPanel1;
    // End of variables declaration//GEN-END:variables

    void init() {
        new ChaoJDialog(this, true).setVisible(true);
        new DangNhapJDialog11(this, true).setVisible(true);
//        login.setVisible(true);
        this.setIconImage(XImage.getApImage());
    }

    void dangXuat() {
        System.exit(0);
    }
}
